# Generated by Django 3.1.3 on 2021-03-21 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id_categoria', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('categoria_nombre', models.CharField(help_text='Título de la categoria', max_length=100)),
                ('categoria_api', models.CharField(default='', help_text='Término de búsqueda en la api', max_length=50)),
                ('creada_el', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Condicion',
            fields=[
                ('id_Condicion', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('articulo', models.TextField(help_text='Escriba aquí sus condiciones')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Condiciones',
            },
        ),
        migrations.CreateModel(
            name='Porfile',
            fields=[
                ('id_porfile', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('imagen_perfil', models.ImageField(default='default/porfile.png', help_text='Imágen de Perfil', upload_to='porfile/images')),
                ('cover', models.ImageField(default='default/cover.png', help_text='Sube tu cover', upload_to='porfile/images/cover')),
                ('bio', models.CharField(blank=True, help_text='Escriba aqui su biografia', max_length=300, null=True)),
                ('vistas', models.IntegerField(default=0)),
                ('website', models.CharField(blank=True, default='', help_text='Ingresa tu sitio web', max_length=100, null=True)),
                ('paypal', models.EmailField(default='', help_text='Tu cuenta de PayPal para recibir los pagos', max_length=254)),
                ('total_post', models.IntegerField(default=0)),
                ('usuario', models.OneToOneField(help_text='Nombre de usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Porfiles',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id_post', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('titulo', models.CharField(help_text='Título del video', max_length=100)),
                ('descripcion', models.CharField(blank=True, default='', help_text='Descripción corta del video', max_length=300, null=True)),
                ('imagen_principal', models.ImageField(help_text='Cover de tu video', upload_to='posts/images')),
                ('video', models.FileField(upload_to='videos/')),
                ('imagen_url', models.CharField(blank=True, default='', help_text='URL de la imagen', max_length=300, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('publicado', models.BooleanField(default=False)),
                ('monetizar', models.BooleanField(default=False, help_text='¿Queires monetizar tu video?')),
                ('visitas', models.IntegerField(default=0)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.porfile')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.categorias')),
            ],
            options={
                'verbose_name_plural': 'Videos',
            },
        ),
        migrations.CreateModel(
            name='Seguidores',
            fields=[
                ('id_seguidor', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('seguiendo_desde', models.DateTimeField(default=django.utils.timezone.now)),
                ('seguido', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Seguido', to=settings.AUTH_USER_MODEL)),
                ('sigue', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Sigue', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Seguidores',
            },
        ),
        migrations.CreateModel(
            name='PostGuardado',
            fields=[
                ('id_post_guardado', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('guardado_el', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Videos Guardados',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_post', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('comentario', models.TextField(help_text='Escriba aquí su comentario')),
                ('publicado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author_comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.porfile')),
                ('post_comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
            ],
            options={
                'verbose_name_plural': 'Comentarios',
            },
        ),
    ]
