# Generated by Django 3.1.3 on 2021-03-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_url',
            field=models.CharField(blank=True, default='', help_text='URL de la imagen', max_length=300, null=True),
        ),
    ]
