# Generated by Django 2.2.10 on 2020-10-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200921_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='porfile',
            name='paypal',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='porfile',
            name='total_post',
            field=models.IntegerField(default=0),
        ),
    ]
