# Generated by Django 2.2.10 on 2020-09-09 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20200909_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='porfile',
            name='seguidor',
        ),
        migrations.CreateModel(
            name='Seguir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('comenzo_a_seguir', models.DateTimeField(default=django.utils.timezone.now)),
                ('sigue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sigue', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguidor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Seguidores',
            },
        ),
    ]
