# Generated by Django 2.2.10 on 2020-09-09 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200909_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguir',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Porfile'),
        ),
    ]
