# Generated by Django 2.2.10 on 2020-09-09 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200909_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguir',
            name='sigue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
