# Generated by Django 3.1.3 on 2021-03-13 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_auto_20201027_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguidores',
            fields=[
                ('id_seguidor', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('seguiendo_desde', models.DateTimeField(default=django.utils.timezone.now)),
                ('sigue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sigue', to=settings.AUTH_USER_MODEL)),
                ('siguido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Seguido', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Seguidores',
            },
        ),
    ]
