# Generated by Django 2.2.10 on 2020-09-09 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200909_1143'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seguir',
        ),
    ]
