# Generated by Django 2.2.10 on 2020-09-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200915_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porfile',
            name='cover',
            field=models.ImageField(default='default/porfile.png', upload_to='porfile/images/cover'),
        ),
    ]
