# Generated by Django 3.1.3 on 2021-03-16 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210313_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='porfile',
            name='email',
        ),
    ]
