# Generated by Django 2.2.10 on 2020-09-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200915_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categoria',
            field=models.CharField(choices=[('hogar', 'HOGAR'), ('deportes', 'DEPORTES'), ('tecnologia', 'TECNOLOGIA'), ('ciencia', 'CIENCIA'), ('salud', 'SALUD'), ('estilodevida', 'ESTILO_DE_VIDA'), ('mundo', 'MUNDO'), ('utilidades', 'UTILIDADES'), ('cocina', 'COCINA'), ('tutoriales', 'TUTORIALES'), ('bloguer', 'BLOGUER'), ('cultura', 'CULTURA'), ('negocios', 'NEGOCIOS'), ('politica', 'POLITICA'), ('opinion', 'OPINION'), ('moda', 'MODA'), ('viajes', 'VIAJES')], default='bloguer', help_text='Categoria del artículo', max_length=20),
        ),
    ]
