# Generated by Django 3.1.3 on 2021-03-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210319_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen_principal',
            field=models.ImageField(default='default/cover.png', help_text='Imágen principal', upload_to='posts/images'),
        ),
    ]
