# Generated by Django 3.1.3 on 2021-03-20 17:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210319_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condicion',
            fields=[
                ('id_Condicion', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('articulo', models.TextField(help_text='Escriba aquí sus condiciones')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Condiciones',
            },
        ),
    ]
