# Generated by Django 3.1.3 on 2021-03-20 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_condicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorias',
            name='categoria_api',
            field=models.CharField(default='', help_text='Término de búsqueda en la api', max_length=50),
        ),
    ]
